addons:
    code_climate:
        repo_token: 887f2b48fc07c69f5ea0fb40b01b9b75a075811d8abaf9e9aa8962db5778f4c2
sudo: false
notifications:
  email: true
language: node_js
node_js:
  - "node"
  # - "6"
  # - "5"
  # - "4"
cache:
  directories:
    - node_modules
install:
  - node --version
  - npm --version
  - npm install
  - npm install -g docco
script: npm test
after_success: npm run coverage
